name = "pub-ecom-catalog-worker"
main = "src/index.ts"
compatibility_date = "2026-08-21"
compatibility_flags = [ "nodejs_compat" ]

[browser]
binding = "BROWSER"

# No custom build command, let wrangler handle it but we will pass flags via CLI if needed.
