name = "pub-ecom-catalog-worker"
main = "src/index.ts"
compatibility_date = "2026-08-21"
compatibility_flags = [ "nodejs_compat" ]

[browser]
binding = "BROWSER"

# Build configuration to handle playwright-core issues
[build.upload]
format = "modules"

[rules]
globs = ["**/*.js"]
type = "ESModule"


[build]
command = "npm run build"

[vars]
# Variáveis de ambiente

