/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAudienceRouteImport } from './routes/dashboard/audience'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard/finance'
import { Route as DashboardLiveRouteImport } from './routes/dashboard/live'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard/marketing'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStoresRouteImport } from './routes/dashboard/stores'
import { Route as PrototypeBDashboardRouteRouteImport } from './routes/prototype-b/dashboard/route'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreConfirmationRouteImport } from './routes/store/confirmation'
import { Route as StoreProductRouteImport } from './routes/store/product'
import { Route as PrototypeBDashboardIndexRouteImport } from './routes/prototype-b/dashboard/index'
import { Route as PrototypeBDashboardAudienceRouteImport } from './routes/prototype-b/dashboard/audience'
import { Route as PrototypeBDashboardFinanceRouteImport } from './routes/prototype-b/dashboard/finance'
import { Route as PrototypeBDashboardInfluencersRouteImport } from './routes/prototype-b/dashboard/influencers'
import { Route as PrototypeBDashboardLiveRouteImport } from './routes/prototype-b/dashboard/live'
import { Route as PrototypeBDashboardMarketingRouteImport } from './routes/prototype-b/dashboard/marketing'
import { Route as PrototypeBDashboardOrdersRouteImport } from './routes/prototype-b/dashboard/orders'
import { Route as PrototypeBDashboardProductsRouteImport } from './routes/prototype-b/dashboard/products'
import { Route as PrototypeBDashboardRankingRouteImport } from './routes/prototype-b/dashboard/ranking'
import { Route as PrototypeBDashboardSettingsRouteImport } from './routes/prototype-b/dashboard/settings'
import { Route as PrototypeBDashboardStoresRouteImport } from './routes/prototype-b/dashboard/stores'
import { Route as PrototypeBDashboardSuppliersRouteImport } from './routes/prototype-b/dashboard/suppliers'
import { Route as PrototypeBStoreIndexRouteImport } from './routes/prototype-b/store/index'
import { Route as PrototypeBStoreCartRouteImport } from './routes/prototype-b/store/cart'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAudienceRoute = DashboardAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStoresRoute = DashboardStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PrototypeBDashboardRouteRoute =
  PrototypeBDashboardRouteRouteImport.update({
    id: '/prototype-b/dashboard',
    path: '/prototype-b/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/store/checkout',
  path: '/store/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreConfirmationRoute = StoreConfirmationRouteImport.update({
  id: '/store/confirmation',
  path: '/store/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreProductRoute = StoreProductRouteImport.update({
  id: '/store/product',
  path: '/store/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeBDashboardIndexRoute =
  PrototypeBDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardAudienceRoute =
  PrototypeBDashboardAudienceRouteImport.update({
    id: '/audience',
    path: '/audience',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardFinanceRoute =
  PrototypeBDashboardFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardInfluencersRoute =
  PrototypeBDashboardInfluencersRouteImport.update({
    id: '/influencers',
    path: '/influencers',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardLiveRoute = PrototypeBDashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => PrototypeBDashboardRouteRoute,
} as any)
const PrototypeBDashboardMarketingRoute =
  PrototypeBDashboardMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardOrdersRoute =
  PrototypeBDashboardOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardProductsRoute =
  PrototypeBDashboardProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardRankingRoute =
  PrototypeBDashboardRankingRouteImport.update({
    id: '/ranking',
    path: '/ranking',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardSettingsRoute =
  PrototypeBDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardStoresRoute =
  PrototypeBDashboardStoresRouteImport.update({
    id: '/stores',
    path: '/stores',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBDashboardSuppliersRoute =
  PrototypeBDashboardSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => PrototypeBDashboardRouteRoute,
  } as any)
const PrototypeBStoreIndexRoute = PrototypeBStoreIndexRouteImport.update({
  id: '/prototype-b/store/',
  path: '/prototype-b/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeBStoreCartRoute = PrototypeBStoreCartRouteImport.update({
  id: '/prototype-b/store/cart',
  path: '/prototype-b/store/cart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/prototype-b/dashboard': typeof PrototypeBDashboardRouteRouteWithChildren
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stores': typeof DashboardStoresRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/confirmation': typeof StoreConfirmationRoute
  '/store/product': typeof StoreProductRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/prototype-b/dashboard/audience': typeof PrototypeBDashboardAudienceRoute
  '/prototype-b/dashboard/finance': typeof PrototypeBDashboardFinanceRoute
  '/prototype-b/dashboard/influencers': typeof PrototypeBDashboardInfluencersRoute
  '/prototype-b/dashboard/live': typeof PrototypeBDashboardLiveRoute
  '/prototype-b/dashboard/marketing': typeof PrototypeBDashboardMarketingRoute
  '/prototype-b/dashboard/orders': typeof PrototypeBDashboardOrdersRoute
  '/prototype-b/dashboard/products': typeof PrototypeBDashboardProductsRoute
  '/prototype-b/dashboard/ranking': typeof PrototypeBDashboardRankingRoute
  '/prototype-b/dashboard/settings': typeof PrototypeBDashboardSettingsRoute
  '/prototype-b/dashboard/stores': typeof PrototypeBDashboardStoresRoute
  '/prototype-b/dashboard/suppliers': typeof PrototypeBDashboardSuppliersRoute
  '/prototype-b/store/cart': typeof PrototypeBStoreCartRoute
  '/prototype-b/dashboard/': typeof PrototypeBDashboardIndexRoute
  '/prototype-b/store/': typeof PrototypeBStoreIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stores': typeof DashboardStoresRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/confirmation': typeof StoreConfirmationRoute
  '/store/product': typeof StoreProductRoute
  '/dashboard': typeof DashboardIndexRoute
  '/store': typeof StoreIndexRoute
  '/prototype-b/dashboard/audience': typeof PrototypeBDashboardAudienceRoute
  '/prototype-b/dashboard/finance': typeof PrototypeBDashboardFinanceRoute
  '/prototype-b/dashboard/influencers': typeof PrototypeBDashboardInfluencersRoute
  '/prototype-b/dashboard/live': typeof PrototypeBDashboardLiveRoute
  '/prototype-b/dashboard/marketing': typeof PrototypeBDashboardMarketingRoute
  '/prototype-b/dashboard/orders': typeof PrototypeBDashboardOrdersRoute
  '/prototype-b/dashboard/products': typeof PrototypeBDashboardProductsRoute
  '/prototype-b/dashboard/ranking': typeof PrototypeBDashboardRankingRoute
  '/prototype-b/dashboard/settings': typeof PrototypeBDashboardSettingsRoute
  '/prototype-b/dashboard/stores': typeof PrototypeBDashboardStoresRoute
  '/prototype-b/dashboard/suppliers': typeof PrototypeBDashboardSuppliersRoute
  '/prototype-b/store/cart': typeof PrototypeBStoreCartRoute
  '/prototype-b/dashboard': typeof PrototypeBDashboardIndexRoute
  '/prototype-b/store': typeof PrototypeBStoreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/prototype-b/dashboard': typeof PrototypeBDashboardRouteRouteWithChildren
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stores': typeof DashboardStoresRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/confirmation': typeof StoreConfirmationRoute
  '/store/product': typeof StoreProductRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/prototype-b/dashboard/audience': typeof PrototypeBDashboardAudienceRoute
  '/prototype-b/dashboard/finance': typeof PrototypeBDashboardFinanceRoute
  '/prototype-b/dashboard/influencers': typeof PrototypeBDashboardInfluencersRoute
  '/prototype-b/dashboard/live': typeof PrototypeBDashboardLiveRoute
  '/prototype-b/dashboard/marketing': typeof PrototypeBDashboardMarketingRoute
  '/prototype-b/dashboard/orders': typeof PrototypeBDashboardOrdersRoute
  '/prototype-b/dashboard/products': typeof PrototypeBDashboardProductsRoute
  '/prototype-b/dashboard/ranking': typeof PrototypeBDashboardRankingRoute
  '/prototype-b/dashboard/settings': typeof PrototypeBDashboardSettingsRoute
  '/prototype-b/dashboard/stores': typeof PrototypeBDashboardStoresRoute
  '/prototype-b/dashboard/suppliers': typeof PrototypeBDashboardSuppliersRoute
  '/prototype-b/store/cart': typeof PrototypeBStoreCartRoute
  '/prototype-b/dashboard/': typeof PrototypeBDashboardIndexRoute
  '/prototype-b/store/': typeof PrototypeBStoreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/prototype-b/dashboard'
    | '/dashboard/audience'
    | '/dashboard/finance'
    | '/dashboard/live'
    | '/dashboard/marketing'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/stores'
    | '/store/checkout'
    | '/store/confirmation'
    | '/store/product'
    | '/dashboard/'
    | '/store/'
    | '/prototype-b/dashboard/audience'
    | '/prototype-b/dashboard/finance'
    | '/prototype-b/dashboard/influencers'
    | '/prototype-b/dashboard/live'
    | '/prototype-b/dashboard/marketing'
    | '/prototype-b/dashboard/orders'
    | '/prototype-b/dashboard/products'
    | '/prototype-b/dashboard/ranking'
    | '/prototype-b/dashboard/settings'
    | '/prototype-b/dashboard/stores'
    | '/prototype-b/dashboard/suppliers'
    | '/prototype-b/store/cart'
    | '/prototype-b/dashboard/'
    | '/prototype-b/store/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/audience'
    | '/dashboard/finance'
    | '/dashboard/live'
    | '/dashboard/marketing'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/stores'
    | '/store/checkout'
    | '/store/confirmation'
    | '/store/product'
    | '/dashboard'
    | '/store'
    | '/prototype-b/dashboard/audience'
    | '/prototype-b/dashboard/finance'
    | '/prototype-b/dashboard/influencers'
    | '/prototype-b/dashboard/live'
    | '/prototype-b/dashboard/marketing'
    | '/prototype-b/dashboard/orders'
    | '/prototype-b/dashboard/products'
    | '/prototype-b/dashboard/ranking'
    | '/prototype-b/dashboard/settings'
    | '/prototype-b/dashboard/stores'
    | '/prototype-b/dashboard/suppliers'
    | '/prototype-b/store/cart'
    | '/prototype-b/dashboard'
    | '/prototype-b/store'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/prototype-b/dashboard'
    | '/dashboard/audience'
    | '/dashboard/finance'
    | '/dashboard/live'
    | '/dashboard/marketing'
    | '/dashboard/orders'
    | '/dashboard/settings'
    | '/dashboard/stores'
    | '/store/checkout'
    | '/store/confirmation'
    | '/store/product'
    | '/dashboard/'
    | '/store/'
    | '/prototype-b/dashboard/audience'
    | '/prototype-b/dashboard/finance'
    | '/prototype-b/dashboard/influencers'
    | '/prototype-b/dashboard/live'
    | '/prototype-b/dashboard/marketing'
    | '/prototype-b/dashboard/orders'
    | '/prototype-b/dashboard/products'
    | '/prototype-b/dashboard/ranking'
    | '/prototype-b/dashboard/settings'
    | '/prototype-b/dashboard/stores'
    | '/prototype-b/dashboard/suppliers'
    | '/prototype-b/store/cart'
    | '/prototype-b/dashboard/'
    | '/prototype-b/store/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PrototypeBDashboardRouteRoute: typeof PrototypeBDashboardRouteRouteWithChildren
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreConfirmationRoute: typeof StoreConfirmationRoute
  StoreProductRoute: typeof StoreProductRoute
  StoreIndexRoute: typeof StoreIndexRoute
  PrototypeBStoreCartRoute: typeof PrototypeBStoreCartRoute
  PrototypeBStoreIndexRoute: typeof PrototypeBStoreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audience': {
      id: '/dashboard/audience'
      path: '/audience'
      fullPath: '/dashboard/audience'
      preLoaderRoute: typeof DashboardAudienceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/stores': {
      id: '/dashboard/stores'
      path: '/stores'
      fullPath: '/dashboard/stores'
      preLoaderRoute: typeof DashboardStoresRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/prototype-b/dashboard': {
      id: '/prototype-b/dashboard'
      path: '/prototype-b/dashboard'
      fullPath: '/prototype-b/dashboard'
      preLoaderRoute: typeof PrototypeBDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/store/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/confirmation': {
      id: '/store/confirmation'
      path: '/store/confirmation'
      fullPath: '/store/confirmation'
      preLoaderRoute: typeof StoreConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/product': {
      id: '/store/product'
      path: '/store/product'
      fullPath: '/store/product'
      preLoaderRoute: typeof StoreProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype-b/dashboard/': {
      id: '/prototype-b/dashboard/'
      path: '/'
      fullPath: '/prototype-b/dashboard/'
      preLoaderRoute: typeof PrototypeBDashboardIndexRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/audience': {
      id: '/prototype-b/dashboard/audience'
      path: '/audience'
      fullPath: '/prototype-b/dashboard/audience'
      preLoaderRoute: typeof PrototypeBDashboardAudienceRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/finance': {
      id: '/prototype-b/dashboard/finance'
      path: '/finance'
      fullPath: '/prototype-b/dashboard/finance'
      preLoaderRoute: typeof PrototypeBDashboardFinanceRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/influencers': {
      id: '/prototype-b/dashboard/influencers'
      path: '/influencers'
      fullPath: '/prototype-b/dashboard/influencers'
      preLoaderRoute: typeof PrototypeBDashboardInfluencersRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/live': {
      id: '/prototype-b/dashboard/live'
      path: '/live'
      fullPath: '/prototype-b/dashboard/live'
      preLoaderRoute: typeof PrototypeBDashboardLiveRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/marketing': {
      id: '/prototype-b/dashboard/marketing'
      path: '/marketing'
      fullPath: '/prototype-b/dashboard/marketing'
      preLoaderRoute: typeof PrototypeBDashboardMarketingRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/orders': {
      id: '/prototype-b/dashboard/orders'
      path: '/orders'
      fullPath: '/prototype-b/dashboard/orders'
      preLoaderRoute: typeof PrototypeBDashboardOrdersRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/products': {
      id: '/prototype-b/dashboard/products'
      path: '/products'
      fullPath: '/prototype-b/dashboard/products'
      preLoaderRoute: typeof PrototypeBDashboardProductsRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/ranking': {
      id: '/prototype-b/dashboard/ranking'
      path: '/ranking'
      fullPath: '/prototype-b/dashboard/ranking'
      preLoaderRoute: typeof PrototypeBDashboardRankingRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/settings': {
      id: '/prototype-b/dashboard/settings'
      path: '/settings'
      fullPath: '/prototype-b/dashboard/settings'
      preLoaderRoute: typeof PrototypeBDashboardSettingsRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/stores': {
      id: '/prototype-b/dashboard/stores'
      path: '/stores'
      fullPath: '/prototype-b/dashboard/stores'
      preLoaderRoute: typeof PrototypeBDashboardStoresRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/dashboard/suppliers': {
      id: '/prototype-b/dashboard/suppliers'
      path: '/suppliers'
      fullPath: '/prototype-b/dashboard/suppliers'
      preLoaderRoute: typeof PrototypeBDashboardSuppliersRouteImport
      parentRoute: typeof PrototypeBDashboardRouteRoute
    }
    '/prototype-b/store/': {
      id: '/prototype-b/store/'
      path: '/prototype-b/store'
      fullPath: '/prototype-b/store/'
      preLoaderRoute: typeof PrototypeBStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype-b/store/cart': {
      id: '/prototype-b/store/cart'
      path: '/prototype-b/store/cart'
      fullPath: '/prototype-b/store/cart'
      preLoaderRoute: typeof PrototypeBStoreCartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAudienceRoute: typeof DashboardAudienceRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStoresRoute: typeof DashboardStoresRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAudienceRoute: DashboardAudienceRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStoresRoute: DashboardStoresRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface PrototypeBDashboardRouteRouteChildren {
  PrototypeBDashboardAudienceRoute: typeof PrototypeBDashboardAudienceRoute
  PrototypeBDashboardFinanceRoute: typeof PrototypeBDashboardFinanceRoute
  PrototypeBDashboardInfluencersRoute: typeof PrototypeBDashboardInfluencersRoute
  PrototypeBDashboardLiveRoute: typeof PrototypeBDashboardLiveRoute
  PrototypeBDashboardMarketingRoute: typeof PrototypeBDashboardMarketingRoute
  PrototypeBDashboardOrdersRoute: typeof PrototypeBDashboardOrdersRoute
  PrototypeBDashboardProductsRoute: typeof PrototypeBDashboardProductsRoute
  PrototypeBDashboardRankingRoute: typeof PrototypeBDashboardRankingRoute
  PrototypeBDashboardSettingsRoute: typeof PrototypeBDashboardSettingsRoute
  PrototypeBDashboardStoresRoute: typeof PrototypeBDashboardStoresRoute
  PrototypeBDashboardSuppliersRoute: typeof PrototypeBDashboardSuppliersRoute
  PrototypeBDashboardIndexRoute: typeof PrototypeBDashboardIndexRoute
}

const PrototypeBDashboardRouteRouteChildren: PrototypeBDashboardRouteRouteChildren =
  {
    PrototypeBDashboardAudienceRoute: PrototypeBDashboardAudienceRoute,
    PrototypeBDashboardFinanceRoute: PrototypeBDashboardFinanceRoute,
    PrototypeBDashboardInfluencersRoute: PrototypeBDashboardInfluencersRoute,
    PrototypeBDashboardLiveRoute: PrototypeBDashboardLiveRoute,
    PrototypeBDashboardMarketingRoute: PrototypeBDashboardMarketingRoute,
    PrototypeBDashboardOrdersRoute: PrototypeBDashboardOrdersRoute,
    PrototypeBDashboardProductsRoute: PrototypeBDashboardProductsRoute,
    PrototypeBDashboardRankingRoute: PrototypeBDashboardRankingRoute,
    PrototypeBDashboardSettingsRoute: PrototypeBDashboardSettingsRoute,
    PrototypeBDashboardStoresRoute: PrototypeBDashboardStoresRoute,
    PrototypeBDashboardSuppliersRoute: PrototypeBDashboardSuppliersRoute,
    PrototypeBDashboardIndexRoute: PrototypeBDashboardIndexRoute,
  }

const PrototypeBDashboardRouteRouteWithChildren =
  PrototypeBDashboardRouteRoute._addFileChildren(
    PrototypeBDashboardRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PrototypeBDashboardRouteRoute: PrototypeBDashboardRouteRouteWithChildren,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreConfirmationRoute: StoreConfirmationRoute,
  StoreProductRoute: StoreProductRoute,
  StoreIndexRoute: StoreIndexRoute,
  PrototypeBStoreCartRoute: PrototypeBStoreCartRoute,
  PrototypeBStoreIndexRoute: PrototypeBStoreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
