/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAffiliatesRouteImport } from './routes/dashboard/affiliates'
import { Route as DashboardAudienceRouteImport } from './routes/dashboard/audience'
import { Route as DashboardBonificationsRouteImport } from './routes/dashboard/bonifications'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard/finance'
import { Route as DashboardInfluencersRouteImport } from './routes/dashboard/influencers'
import { Route as DashboardIngestionRouteImport } from './routes/dashboard/ingestion'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardLiveRouteImport } from './routes/dashboard/live'
import { Route as DashboardMarketingRouteImport } from './routes/dashboard/marketing'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardProductsRouteImport } from './routes/dashboard/products'
import { Route as DashboardRankingRouteImport } from './routes/dashboard/ranking'
import { Route as DashboardSeoRouteImport } from './routes/dashboard/seo'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardStoresRouteImport } from './routes/dashboard/stores'
import { Route as DashboardTrackingRouteImport } from './routes/dashboard/tracking'
import { Route as StoreIndexRouteImport } from './routes/store/index'
import { Route as StoreCartRouteImport } from './routes/store/cart'
import { Route as StoreCheckoutRouteImport } from './routes/store/checkout'
import { Route as StoreConfirmationRouteImport } from './routes/store/confirmation'
import { Route as ApiCatalogHealthRouteImport } from './routes/api/catalog/health'
import { Route as ApiCatalogStatsRouteImport } from './routes/api/catalog/stats'
import { Route as ApiIngestionShopeeRouteImport } from './routes/api/ingestion/shopee'
import { Route as DashboardStoresStoreIdRouteImport } from './routes/dashboard/stores.$storeId'
import { Route as DashboardSuppliersIndexRouteImport } from './routes/dashboard/suppliers/index'
import { Route as DashboardSuppliersIngestionRouteImport } from './routes/dashboard/suppliers/ingestion'
import { Route as ApiCatalogStoresStoreIdRefreshRouteImport } from './routes/api/catalog/stores/$storeId.refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAffiliatesRoute = DashboardAffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAudienceRoute = DashboardAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBonificationsRoute = DashboardBonificationsRouteImport.update({
  id: '/bonifications',
  path: '/bonifications',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInfluencersRoute = DashboardInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardIngestionRoute = DashboardIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMarketingRoute = DashboardMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRankingRoute = DashboardRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSeoRoute = DashboardSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardStoresRoute = DashboardStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTrackingRoute = DashboardTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const StoreIndexRoute = StoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCartRoute = StoreCartRouteImport.update({
  id: '/store/cart',
  path: '/store/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreCheckoutRoute = StoreCheckoutRouteImport.update({
  id: '/store/checkout',
  path: '/store/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreConfirmationRoute = StoreConfirmationRouteImport.update({
  id: '/store/confirmation',
  path: '/store/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogHealthRoute = ApiCatalogHealthRouteImport.update({
  id: '/api/catalog/health',
  path: '/api/catalog/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogStatsRoute = ApiCatalogStatsRouteImport.update({
  id: '/api/catalog/stats',
  path: '/api/catalog/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestionShopeeRoute = ApiIngestionShopeeRouteImport.update({
  id: '/api/ingestion/shopee',
  path: '/api/ingestion/shopee',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStoresStoreIdRoute = DashboardStoresStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => DashboardStoresRoute,
} as any)
const DashboardSuppliersIndexRoute = DashboardSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSuppliersIngestionRoute =
  DashboardSuppliersIngestionRouteImport.update({
    id: '/suppliers/ingestion',
    path: '/suppliers/ingestion',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiCatalogStoresStoreIdRefreshRoute =
  ApiCatalogStoresStoreIdRefreshRouteImport.update({
    id: '/api/catalog/stores/$storeId/refresh',
    path: '/api/catalog/stores/$storeId/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/affiliates': typeof DashboardAffiliatesRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/bonifications': typeof DashboardBonificationsRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/ingestion': typeof DashboardIngestionRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/ranking': typeof DashboardRankingRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stores': typeof DashboardStoresRouteWithChildren
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/store/cart': typeof StoreCartRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/confirmation': typeof StoreConfirmationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/catalog/health': typeof ApiCatalogHealthRoute
  '/api/catalog/stats': typeof ApiCatalogStatsRoute
  '/api/ingestion/shopee': typeof ApiIngestionShopeeRoute
  '/dashboard/stores/$storeId': typeof DashboardStoresStoreIdRoute
  '/dashboard/suppliers/ingestion': typeof DashboardSuppliersIngestionRoute
  '/dashboard/suppliers/': typeof DashboardSuppliersIndexRoute
  '/api/catalog/stores/$storeId/refresh': typeof ApiCatalogStoresStoreIdRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/affiliates': typeof DashboardAffiliatesRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/bonifications': typeof DashboardBonificationsRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/ingestion': typeof DashboardIngestionRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/ranking': typeof DashboardRankingRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stores': typeof DashboardStoresRouteWithChildren
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/store/cart': typeof StoreCartRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/confirmation': typeof StoreConfirmationRoute
  '/dashboard': typeof DashboardIndexRoute
  '/store': typeof StoreIndexRoute
  '/api/catalog/health': typeof ApiCatalogHealthRoute
  '/api/catalog/stats': typeof ApiCatalogStatsRoute
  '/api/ingestion/shopee': typeof ApiIngestionShopeeRoute
  '/dashboard/stores/$storeId': typeof DashboardStoresStoreIdRoute
  '/dashboard/suppliers/ingestion': typeof DashboardSuppliersIngestionRoute
  '/dashboard/suppliers': typeof DashboardSuppliersIndexRoute
  '/api/catalog/stores/$storeId/refresh': typeof ApiCatalogStoresStoreIdRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/affiliates': typeof DashboardAffiliatesRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/bonifications': typeof DashboardBonificationsRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/ingestion': typeof DashboardIngestionRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/marketing': typeof DashboardMarketingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/ranking': typeof DashboardRankingRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/stores': typeof DashboardStoresRouteWithChildren
  '/dashboard/tracking': typeof DashboardTrackingRoute
  '/store/cart': typeof StoreCartRoute
  '/store/checkout': typeof StoreCheckoutRoute
  '/store/confirmation': typeof StoreConfirmationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/store/': typeof StoreIndexRoute
  '/api/catalog/health': typeof ApiCatalogHealthRoute
  '/api/catalog/stats': typeof ApiCatalogStatsRoute
  '/api/ingestion/shopee': typeof ApiIngestionShopeeRoute
  '/dashboard/stores/$storeId': typeof DashboardStoresStoreIdRoute
  '/dashboard/suppliers/ingestion': typeof DashboardSuppliersIngestionRoute
  '/dashboard/suppliers/': typeof DashboardSuppliersIndexRoute
  '/api/catalog/stores/$storeId/refresh': typeof ApiCatalogStoresStoreIdRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/dashboard/affiliates'
    | '/dashboard/audience'
    | '/dashboard/bonifications'
    | '/dashboard/finance'
    | '/dashboard/influencers'
    | '/dashboard/ingestion'
    | '/dashboard/inventory'
    | '/dashboard/live'
    | '/dashboard/marketing'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/ranking'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/stores'
    | '/dashboard/tracking'
    | '/store/cart'
    | '/store/checkout'
    | '/store/confirmation'
    | '/dashboard/'
    | '/store/'
    | '/api/catalog/health'
    | '/api/catalog/stats'
    | '/api/ingestion/shopee'
    | '/dashboard/stores/$storeId'
    | '/dashboard/suppliers/ingestion'
    | '/dashboard/suppliers/'
    | '/api/catalog/stores/$storeId/refresh'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/dashboard/affiliates'
    | '/dashboard/audience'
    | '/dashboard/bonifications'
    | '/dashboard/finance'
    | '/dashboard/influencers'
    | '/dashboard/ingestion'
    | '/dashboard/inventory'
    | '/dashboard/live'
    | '/dashboard/marketing'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/ranking'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/stores'
    | '/dashboard/tracking'
    | '/store/cart'
    | '/store/checkout'
    | '/store/confirmation'
    | '/dashboard'
    | '/store'
    | '/api/catalog/health'
    | '/api/catalog/stats'
    | '/api/ingestion/shopee'
    | '/dashboard/stores/$storeId'
    | '/dashboard/suppliers/ingestion'
    | '/dashboard/suppliers'
    | '/api/catalog/stores/$storeId/refresh'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/dashboard/affiliates'
    | '/dashboard/audience'
    | '/dashboard/bonifications'
    | '/dashboard/finance'
    | '/dashboard/influencers'
    | '/dashboard/ingestion'
    | '/dashboard/inventory'
    | '/dashboard/live'
    | '/dashboard/marketing'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/dashboard/ranking'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/stores'
    | '/dashboard/tracking'
    | '/store/cart'
    | '/store/checkout'
    | '/store/confirmation'
    | '/dashboard/'
    | '/store/'
    | '/api/catalog/health'
    | '/api/catalog/stats'
    | '/api/ingestion/shopee'
    | '/dashboard/stores/$storeId'
    | '/dashboard/suppliers/ingestion'
    | '/dashboard/suppliers/'
    | '/api/catalog/stores/$storeId/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StoreCartRoute: typeof StoreCartRoute
  StoreCheckoutRoute: typeof StoreCheckoutRoute
  StoreConfirmationRoute: typeof StoreConfirmationRoute
  StoreIndexRoute: typeof StoreIndexRoute
  ApiCatalogHealthRoute: typeof ApiCatalogHealthRoute
  ApiCatalogStatsRoute: typeof ApiCatalogStatsRoute
  ApiIngestionShopeeRoute: typeof ApiIngestionShopeeRoute
  ApiCatalogStoresStoreIdRefreshRoute: typeof ApiCatalogStoresStoreIdRefreshRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/affiliates': {
      id: '/dashboard/affiliates'
      path: '/affiliates'
      fullPath: '/dashboard/affiliates'
      preLoaderRoute: typeof DashboardAffiliatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/audience': {
      id: '/dashboard/audience'
      path: '/audience'
      fullPath: '/dashboard/audience'
      preLoaderRoute: typeof DashboardAudienceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bonifications': {
      id: '/dashboard/bonifications'
      path: '/bonifications'
      fullPath: '/dashboard/bonifications'
      preLoaderRoute: typeof DashboardBonificationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/influencers': {
      id: '/dashboard/influencers'
      path: '/influencers'
      fullPath: '/dashboard/influencers'
      preLoaderRoute: typeof DashboardInfluencersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ingestion': {
      id: '/dashboard/ingestion'
      path: '/ingestion'
      fullPath: '/dashboard/ingestion'
      preLoaderRoute: typeof DashboardIngestionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/marketing': {
      id: '/dashboard/marketing'
      path: '/marketing'
      fullPath: '/dashboard/marketing'
      preLoaderRoute: typeof DashboardMarketingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ranking': {
      id: '/dashboard/ranking'
      path: '/ranking'
      fullPath: '/dashboard/ranking'
      preLoaderRoute: typeof DashboardRankingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/seo': {
      id: '/dashboard/seo'
      path: '/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof DashboardSeoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/stores': {
      id: '/dashboard/stores'
      path: '/stores'
      fullPath: '/dashboard/stores'
      preLoaderRoute: typeof DashboardStoresRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tracking': {
      id: '/dashboard/tracking'
      path: '/tracking'
      fullPath: '/dashboard/tracking'
      preLoaderRoute: typeof DashboardTrackingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/store/': {
      id: '/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof StoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/cart': {
      id: '/store/cart'
      path: '/store/cart'
      fullPath: '/store/cart'
      preLoaderRoute: typeof StoreCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/checkout': {
      id: '/store/checkout'
      path: '/store/checkout'
      fullPath: '/store/checkout'
      preLoaderRoute: typeof StoreCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/confirmation': {
      id: '/store/confirmation'
      path: '/store/confirmation'
      fullPath: '/store/confirmation'
      preLoaderRoute: typeof StoreConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/health': {
      id: '/api/catalog/health'
      path: '/api/catalog/health'
      fullPath: '/api/catalog/health'
      preLoaderRoute: typeof ApiCatalogHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog/stats': {
      id: '/api/catalog/stats'
      path: '/api/catalog/stats'
      fullPath: '/api/catalog/stats'
      preLoaderRoute: typeof ApiCatalogStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingestion/shopee': {
      id: '/api/ingestion/shopee'
      path: '/api/ingestion/shopee'
      fullPath: '/api/ingestion/shopee'
      preLoaderRoute: typeof ApiIngestionShopeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stores/$storeId': {
      id: '/dashboard/stores/$storeId'
      path: '/$storeId'
      fullPath: '/dashboard/stores/$storeId'
      preLoaderRoute: typeof DashboardStoresStoreIdRouteImport
      parentRoute: typeof DashboardStoresRoute
    }
    '/dashboard/suppliers/': {
      id: '/dashboard/suppliers/'
      path: '/suppliers'
      fullPath: '/dashboard/suppliers/'
      preLoaderRoute: typeof DashboardSuppliersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/suppliers/ingestion': {
      id: '/dashboard/suppliers/ingestion'
      path: '/suppliers/ingestion'
      fullPath: '/dashboard/suppliers/ingestion'
      preLoaderRoute: typeof DashboardSuppliersIngestionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/catalog/stores/$storeId/refresh': {
      id: '/api/catalog/stores/$storeId/refresh'
      path: '/api/catalog/stores/$storeId/refresh'
      fullPath: '/api/catalog/stores/$storeId/refresh'
      preLoaderRoute: typeof ApiCatalogStoresStoreIdRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardStoresRouteChildren {
  DashboardStoresStoreIdRoute: typeof DashboardStoresStoreIdRoute
}

const DashboardStoresRouteChildren: DashboardStoresRouteChildren = {
  DashboardStoresStoreIdRoute: DashboardStoresStoreIdRoute,
}

const DashboardStoresRouteWithChildren = DashboardStoresRoute._addFileChildren(
  DashboardStoresRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardAffiliatesRoute: typeof DashboardAffiliatesRoute
  DashboardAudienceRoute: typeof DashboardAudienceRoute
  DashboardBonificationsRoute: typeof DashboardBonificationsRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardInfluencersRoute: typeof DashboardInfluencersRoute
  DashboardIngestionRoute: typeof DashboardIngestionRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardMarketingRoute: typeof DashboardMarketingRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardRankingRoute: typeof DashboardRankingRoute
  DashboardSeoRoute: typeof DashboardSeoRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStoresRoute: typeof DashboardStoresRouteWithChildren
  DashboardTrackingRoute: typeof DashboardTrackingRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSuppliersIngestionRoute: typeof DashboardSuppliersIngestionRoute
  DashboardSuppliersIndexRoute: typeof DashboardSuppliersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAffiliatesRoute: DashboardAffiliatesRoute,
  DashboardAudienceRoute: DashboardAudienceRoute,
  DashboardBonificationsRoute: DashboardBonificationsRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardInfluencersRoute: DashboardInfluencersRoute,
  DashboardIngestionRoute: DashboardIngestionRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardMarketingRoute: DashboardMarketingRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardRankingRoute: DashboardRankingRoute,
  DashboardSeoRoute: DashboardSeoRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStoresRoute: DashboardStoresRouteWithChildren,
  DashboardTrackingRoute: DashboardTrackingRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSuppliersIngestionRoute: DashboardSuppliersIngestionRoute,
  DashboardSuppliersIndexRoute: DashboardSuppliersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StoreCartRoute: StoreCartRoute,
  StoreCheckoutRoute: StoreCheckoutRoute,
  StoreConfirmationRoute: StoreConfirmationRoute,
  StoreIndexRoute: StoreIndexRoute,
  ApiCatalogHealthRoute: ApiCatalogHealthRoute,
  ApiCatalogStatsRoute: ApiCatalogStatsRoute,
  ApiIngestionShopeeRoute: ApiIngestionShopeeRoute,
  ApiCatalogStoresStoreIdRefreshRoute: ApiCatalogStoresStoreIdRefreshRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
