// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function cleanStaleStorage() {
  if (typeof window === 'undefined') return;
  try {
    // Only clean session keys that are definitely not related to the current Supabase project URL
    const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
    if (!SUPABASE_URL) return;
    
    // Extract project ID from URL (e.g., https://xyz.supabase.co -> xyz)
    const currentProjectId = SUPABASE_URL.split('.')[0].split('//')[1];
    
    const keysToRemove: string[] = [];
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.startsWith('sb-') && key.endsWith('-auth-token')) {
        // If it's a supabase auth key but doesn't match current project OR the temporary one, remove it
        if (!key.includes(currentProjectId) && !key.includes('vtcnundfslqqlxdyrogv')) {
          keysToRemove.push(key);
        }
      }
    }
    keysToRemove.forEach((k) => {
      console.warn(`[SupabaseAuth] Limpando chave de sessão de projeto diferente: ${k}`);
      localStorage.removeItem(k);
    });
  } catch {}
}

const OFFICIAL_SUPABASE_URL = 'https://vtcnundfslqqlxdyrogv.supabase.co';
const OFFICIAL_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0Y251bmRmc2xxcWx4ZHlyb2d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1MDgwODUsImV4cCI6MjEwMzA4NDA4NX0.aPEa_lbTAoyBaXQooZ1mUMJuMhsurJMm_Ni7sS1TurU';

function createSupabaseClient() {
  cleanStaleStorage();

  // Strictly bind to the official Supabase project vtcnundfslqqlxdyrogv
  const rawUrl = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const rawKey = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  const SUPABASE_URL = (rawUrl && rawUrl.includes('vtcnundfslqqlxdyrogv')) ? rawUrl : OFFICIAL_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = (rawKey && !rawUrl?.includes('rouxgtjonfncswsqlcgz')) ? rawKey : OFFICIAL_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

